import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Project Marigold",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen h-[100dvh]">
          <Header />
          <div className="w-full h-[calc(100%-60px)] md:h-[calc(100%-100px)]">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
